<?php
/**
 *
 * Data module for shop currencies
 *
 * @package    VirtueMart
 * @subpackage Currency
 * @author RickG
 * @author Max Milbers
 * @link http://www.virtuemart.net
 * @copyright Copyright (c) 2004 - 2010 VirtueMart Team. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
 * VirtueMart is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * @version $Id: currency.php 8970 2015-09-06 23:19:17Z Milbo $
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

if (!class_exists('VmModel')) require(VMPATH_ADMIN . DS . 'helpers' . DS . 'tsmmodel.php');

/**
 * Model class for shop Currencies
 *
 * @package    VirtueMart
 * @subpackage Currency
 */
class VirtueMartModelDateAvailability extends VmModel
{


    /**
     * constructs a VmModel
     * setMainTable defines the maintable of the model
     * @author Max Milbers
     */
    function __construct()
    {
        parent::__construct();
        $this->setMainTable('dateavailability');
    }

    /**
     * Retrieve the detail record for the current $id if the data has not already been loaded.
     *
     * @author Max Milbers
     */
    function getdateavailability($virtuemart_service_class_id,$virtuemart_product_id)
    {
        $db=JFactory::getDbo();
        $query=$db->getQuery(true);
        $query->select('date')
            ->from('#__virtuemart_date_availability')
            ->where('virtuemart_service_class_id='.(int)$virtuemart_service_class_id)
            ->where('virtuemart_product_id='.(int)$virtuemart_product_id)
            ;
        $list=$db->setQuery($query)->loadColumn();
        return $list;

    }


    /**
     * Retireve a list of currencies from the database.
     * This function is used in the backend for the currency listing, therefore no asking if enabled or not
     * @author Max Milbers
     * @return object List of currency objects
     */
    public function populateState($ordering = null, $direction = null)
    {

        parent::populateState($ordering, $direction); // TODO: Change the autogenerated stub
    }

    function getItemList($search='') {
        //echo $this->getListQuery()->dump();
        $items=parent::getItems();
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmprice.php';
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmpromotion.php';
        foreach($items as &$item)
        {
            $item->sale_price_adult=vmprice::get_sale_price_by_mark_up_and_tax($item->price_adult,$item->mark_up_adult,$item->mark_up_price_adult,$item->tax,$item->mark_up_type);
            $item->sale_promotion_price_adult=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_adult,
                $item->mark_up_promotion_adult,$item->mark_up_promotion_price_adult,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_adult,$item->mark_up_promotion_net_adult,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

        }
        return $items;
    }

    function getListQuery()
    {
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmgroupsize.php';
        $app=JFactory::getApplication();
        $input=$app->input;
        $virtuemart_product_id=$input->getInt('virtuemart_product_id',0);
        $db = JFactory::getDbo();
        $query=$db->getQuery(true);
        $virtuemart_date_availability_id=$this->getState('filter.virtuemart_date_availability_id');

        $query->select('dateavailability.date')
            ->from('#__virtuemart_date_availability AS dateavailability')
            ->rightJoin('#__virtuemart_tour_id_service_class_id AS tour_id_service_class_id ON tour_id_service_class_id.virtuemart_product_id=dateavailability.virtuemart_product_id')
            ->leftJoin('#__virtuemart_service_class AS service_class ON service_class.virtuemart_service_class_id=tour_id_service_class_id.virtuemart_service_class_id')
            ->select('service_class.virtuemart_service_class_id,service_class.service_class_name')

            ->leftJoin('#__virtuemart_products_en_gb AS products_en_gb ON products_en_gb.virtuemart_product_id=tour_id_service_class_id.virtuemart_product_id')
            ->select('products_en_gb.virtuemart_product_id')
            ->select('products_en_gb.product_name')
            ->select('GROUP_CONCAT(dateavailability.date) AS dates')



            ->leftJoin('#__virtuemart_products AS products ON products.virtuemart_product_id=tour_id_service_class_id.virtuemart_product_id')
            ->where('products.price_type!='.$query->q(tsmGroupSize::FLAT_PRICE))
            ->group('tour_id_service_class_id.id')
            ->leftJoin('#__users AS users ON users.id=products.assign_user_id')
            ->select('users.name AS assign_user_name')
        ;
        if($virtuemart_date_availability_id)
        {
            $query->where('dateavailability.virtuemart_date_availability_id='.(int)$virtuemart_date_availability_id);
        }
        if($virtuemart_product_id)
        {
            $query->where('dateavailability.virtuemart_product_id='.(int)$virtuemart_product_id);
        }
        $user = JFactory::getUser();
        $shared = '';
        if (vmAccess::manager()) {
            //$query->where('transferaddon.shared=1','OR');
        }
        $search=vRequest::getCmd('search', false);
        if (empty($search)) {
            $search = vRequest::getString('search', false);
        }
        // add filters
        if ($search) {
            $db = JFactory::getDBO();
            $search = '"%' . $db->escape($search, true) . '%"';
            $query->where('dateavailability.dateavailability_name LIKE '.$search);
        }

        // Add the list ordering clause.
        $orderCol = $this->state->get('list.ordering', 'tour_id_service_class_id.id');
        $orderDirn = $this->state->get('list.direction', 'asc');

        if ($orderCol == 'airport.ordering')
        {
            $orderCol = $db->quoteName('dateavailability.virtuemart_date_availability_id') . ' ' . $orderDirn . ', ' . $db->quoteName('itinerary.ordering');
        }

        $query->order($db->escape($orderCol . ' ' . $orderDirn));
        $query->group('tour_id_service_class_id.id');
        echo $query->dump();
        return $query;
    }



    public function save_dateavailability_item($data)
    {
        $virtuemart_product_id=$data['tour_id'];
        $dateavailability_name=$data['dateavailability_name'];
        $tour_service_class_id=$data['tour_service_class_id'];
        if($dateavailability_name=='')
        {
            vmError('please set dateavailability name');
            return false;
        }
        $list_basic_available2=$this->get_dateavailability_item($data);
        if(count($list_basic_available2)==0)
        {
            vmError('there are no dateavailability available');
            return false;
        }
        $list_date_available=array();
        if(count($list_basic_available2))
        {
            foreach($list_basic_available2 as $item)
            {
                $list_date_available[]=$item->date_select;
            }
        }
        //lấy ra group_size_id từ bản ghi đầu tiên
        $virtuemart_group_size_id=reset($list_basic_available2)->virtuemart_group_size_id;
        $list_date_available='"'.implode('","',$list_date_available).'"';
        //check exists data
        $db=JFactory::getDbo();
        $query=$db->getQuery(true);
        $query->select('virtuemart_date_availability_id')
            ->from('#__virtuemart_dateavailability')
            ->where('dateavailability_date IN('.$list_date_available.')')
            ->where('virtuemart_product_id='.(int)$virtuemart_product_id)
            ->where('virtuemart_service_class_id='.(int)$tour_service_class_id)
            ->where('virtuemart_group_size_id='.(int)$virtuemart_group_size_id)
            ;
        $list_virtuemart_date_availability_id=$db->setQuery($query)->loadObjectList();
        if(count($list_virtuemart_date_availability_id)>1)
        {
            vmError('there are some dateavailability exists');
            return false;
        }
        $virtuemart_date_availability_id=parent::store($data);
        $db=JFactory::getDbo();
        if(!$virtuemart_date_availability_id)
        {
            vmError('can not save dateavailability '.$db->getErrorMsg());
            return false;
        }
        
        $query=$db->getQuery(true);
        $table_dateavailability=tsmTable::getInstance('dateavailability','Table');
        $table_dateavailability->bind($data);

        $table_dateavailability->store();
        $virtuemart_date_availability_id=$table_dateavailability->virtuemart_date_availability_id;
        //inser to group size
        foreach($list_basic_available2 as $item)
        {
            $table_dateavailability->virtuemart_date_availability_id=0;
            $table_dateavailability->published=1;
            $table_dateavailability->virtuemart_date_availability_id=$virtuemart_date_availability_id;
            $table_dateavailability->virtuemart_product_id=$virtuemart_product_id;
            $table_dateavailability->dateavailability_date=JFactory::getDate($item->date_select)->toSql();
            $table_dateavailability->virtuemart_service_class_id=$item->service_class_id;
            $table_dateavailability->virtuemart_group_size_id=$item->virtuemart_group_size_id;
            $table_dateavailability->senior_price=$item->senior_price;
            $table_dateavailability->adult_price=$item->price_adult;
            $table_dateavailability->teen_price=$item->price_teen;
            $table_dateavailability->infant_price=$item->price_infant;
            $table_dateavailability->children1_price=$item->price_children1;
            $table_dateavailability->children2_price=$item->price_children2;
            $table_dateavailability->private_room_price=$item->price_private_room;
            $table_dateavailability->senior_dateavailability_price=$item->dateavailability_price->price_senior;
            $table_dateavailability->adult_dateavailability_price=$item->dateavailability_price->price_adult;
            $table_dateavailability->teen_dateavailability_price=$item->dateavailability_price->price_teen;
            $table_dateavailability->infant_dateavailability_price=$item->dateavailability_price->price_infant;
            $table_dateavailability->children1_dateavailability_price=$item->dateavailability_price->price_children1;
            $table_dateavailability->children2_dateavailability_price=$item->dateavailability_price->price_children2;
            $table_dateavailability->private_room_dateavailability_price=$item->dateavailability_price->price_private_room;
            $table_dateavailability->store();
            $err = $db->getErrorMsg();
            if(!empty($err)){
                vmError('can not insert group size in this tour',$err);
            }
        }
        $table_dateavailability->delete($virtuemart_date_availability_id);
        $err = $db->getErrorMsg();
        if(!empty($err)){
            vmError('can not insert group size in this tour',$err);
        }
        return $list_basic_available2;
    }
    public function get_dateavailability_item($data=array())
    {
        $app=JFactory::getApplication();
        $input=$app->input;
        $weeklies=$data['weekly'];
        $a_list_date=$data['list_date'];
        $min_space=$data['min_space'];
        if($min_space==0)
        {
            vmError('please set min space ');
            return false;
        }
        $tour_id=$data['tour_id'];
        if($tour_id==0)
        {
            vmError('please set tour ');
            return false;
        }
        $virtuemart_service_class_id=$data['tour_service_class_id'];
        if($virtuemart_service_class_id==0)
        {
            vmError('please set tour class ');
            return false;
        }
        $vail_period_from=JFactory::getDate($data['vail_period_from']);
        $vail_period_to=JFactory::getDate( $data['vail_period_to']);
        $date_type=$data['date_type'];
        if($date_type=='weekly'&&count($weeklies)==0)
        {
            vmError('please select dates ');
            return false;
        }
        if($date_type=='day_select'&&count($a_list_date)==0)
        {
            vmError('please select dates ');
            return false;
        }

        // Start date
        $date = JFactory::getDate($vail_period_from);
        // End date
        $end_date = JFactory::getDate($vail_period_to);
        $list_date=array();
        while ($date->getTimestamp() <= $end_date->getTimestamp()) {
            $day_of_week = date( "w", $date->getTimestamp());

            if($date_type=='weekly' && count($weeklies))
            {
                if(in_array($day_of_week,$weeklies))
                {
                    $list_date[]= $date->format('Y-m-d');
                }
                $date->modify('+1 day');
                continue;
            }
            if($date_type=='day_select' && count($a_list_date))
            {
                if(in_array($date->format('Y-m-d'),$a_list_date))
                {
                    $list_date[]= $date->format('Y-m-d');
                }
                $date->modify('+1 day');
                continue;
            }
            if(!count($weeklies)&&!count($a_list_date))
            {
                $list_date[]= $date->format('Y-m-d');
                $date->modify('+1 day');
                continue;
            }

        }
        //lấy ra các dateavailability theo điều kiện tour_id, tour class và group size
        $db=JFactory::getDbo();
        $query=$db->getQuery(true);

        //get list group size by tour id
        $query->select('group_size.*')
            ->from('#__virtuemart_tour_id_group_size_id AS tour_id_group_size_id')
            ->where('tour_id_group_size_id.virtuemart_product_id='.(int)$tour_id)
            ->leftJoin('#__virtuemart_group_size AS group_size ON group_size.virtuemart_group_size_id=tour_id_group_size_id.virtuemart_group_size_id')
            ->order('group_size.from')
            ->where('group_size.from>='.(int)$min_space.' OR (group_size.from<='.(int)$min_space.' AND group_size.to>='.(int)$min_space.')')
            ;
        $group_size=$db->setQuery($query)->loadObject();
        if(!$group_size)
        {
            vmError('there no group size from '.(int)$min_space);
            return false;
        }

        $query->clear()
            ->select('group_size_id_tour_dateavailability_price_id.*')
            ->from('#__virtuemart_group_size_id_tour_dateavailability_price_id AS group_size_id_tour_dateavailability_price_id')
            ->leftJoin('#__virtuemart_tour_dateavailability_price AS dateavailability_price
			ON dateavailability_price.virtuemart_dateavailability_price_id=group_size_id_tour_dateavailability_price_id.virtuemart_tour_dateavailability_price_id')
            ->select('dateavailability_price.*')
            ->where('dateavailability_price.virtuemart_product_id='.(int)$tour_id)
            ->where('dateavailability_price.virtuemart_service_class_id='.(int)$virtuemart_service_class_id)
            ->where('group_size_id_tour_dateavailability_price_id.virtuemart_group_size_id='.(int)$group_size->virtuemart_group_size_id)
        ;

        $list_dateavailability_price=$db->setQuery($query)->loadObjectList();
        if(count($list_dateavailability_price)==0)
        {
            vmWarn('there are no dateavailability price ');
        }
        //lấy giá có dateavailability lọc theo điều kiện thỏa mãn danh sách này
        $list_dateavailability_available=array();
        foreach($list_date as $item_date)
        {
            $time_stamp_item_date=JFactory::getDate($item_date)->getTimestamp();
            foreach($list_dateavailability_price as $item_dateavailability_price_date)
            {
                $start_date=$item_dateavailability_price_date->sale_period_from;
                $end_date=$item_dateavailability_price_date->sale_period_to;
                $time_stamp_start_date=JFactory::getDate($start_date)->getTimestamp();
                $time_stamp_end_date=JFactory::getDate($end_date)->getTimestamp();
                if($time_stamp_item_date>=$time_stamp_start_date && $time_stamp_item_date<=$time_stamp_end_date)
                {
                    $item_dateavailability_price_date1=clone $item_dateavailability_price_date;
                    $item_dateavailability_price_date1->date_select=$item_date;
                    $list_dateavailability_available[]=$item_dateavailability_price_date1;
                }
            }
        }
        //lấy ra giá có markup (giá trị dateavailability) theo tour có net dateavailability price
        $list_mark_up_tour_dateavailability_net_price=array();
        $list_virtuemart_dateavailability_price_id=array();
        foreach($list_dateavailability_price as $item_dateavailability_price)
        {
            if(!in_array($item_dateavailability_price->virtuemart_dateavailability_price_id,$list_virtuemart_dateavailability_price_id))
            {
                $list_virtuemart_dateavailability_price_id[]=$item_dateavailability_price->virtuemart_dateavailability_price_id;
            }
        }
        if(count($list_virtuemart_dateavailability_price_id)>=1) {
            $query->clear()
                ->from('#__virtuemart_mark_up_tour_dateavailability_net_price_id AS mark_up_tour_dateavailability_net_price_id')
                ->select('mark_up_tour_dateavailability_net_price_id.*')
                ->where('mark_up_tour_dateavailability_net_price_id.virtuemart_tour_dateavailability_price_id IN ('.implode(',', $list_virtuemart_dateavailability_price_id).')')
            ;

            $list_mark_up_tour_dateavailability_net_price=$db->setQuery($query)->loadObjectList();
        }
        $list_mark_up_tour_dateavailability_net_price2=array();
        foreach($list_mark_up_tour_dateavailability_net_price as $mark_up_tour_dateavailability_net_price)
        {
            $virtuemart_tour_dateavailability_price_id=$mark_up_tour_dateavailability_net_price->virtuemart_tour_dateavailability_price_id;
            $list_mark_up_tour_dateavailability_net_price2[$virtuemart_tour_dateavailability_price_id][$mark_up_tour_dateavailability_net_price->type]=$mark_up_tour_dateavailability_net_price;
        }
        if(count($list_dateavailability_available)==0)
        {
            vmWarn('there are no dateavailability price ');
        }
        //tính giá lãi có dateavailability
        //1.tính giá thực sau khi dateavailability
        foreach($list_dateavailability_available as $key=> $dateavailability_available)
        {
            $virtuemart_dateavailability_price_id=$dateavailability_available->virtuemart_dateavailability_price_id;

            $percent_price=$list_mark_up_tour_dateavailability_net_price2[$virtuemart_dateavailability_price_id]['percent'];
            if(
                $percent_price->senior!=0
                ||$percent_price->adult!=0
                || $percent_price->teen!=0
                || $percent_price->infant!=0
                || $percent_price->children1!=0
                || $percent_price->children2!=0
                || $percent_price->private_room!=0)
            {
                //giá ???c tính theo percent thì không tính theo amount n?a
                $price_senior=$list_dateavailability_available[$key]->price_senior;
                $price_senior=$price_senior-($price_senior*$percent_price->senior)/100;
                $list_dateavailability_available[$key]->price_senior=$price_senior;

                $price_adult=$list_dateavailability_available[$key]->price_adult;
                $price_adult=$price_adult-($price_adult*$percent_price->adult)/100;
                $list_dateavailability_available[$key]->price_adult=$price_adult;

                $price_teen=$list_dateavailability_available[$key]->price_teen;
                $price_teen=$price_teen-($price_teen*$percent_price->teen)/100;
                $list_dateavailability_available[$key]->price_teen=$price_teen;

                $price_infant=$list_dateavailability_available[$key]->price_infant;
                $price_infant=$price_infant-($price_infant*$percent_price->infant)/100;
                $list_dateavailability_available[$key]->price_infant=$price_infant;

                $price_children1=$list_dateavailability_available[$key]->price_children1;
                $price_children1=$price_children1-($price_children1*$percent_price->children1)/100;
                $list_dateavailability_available[$key]->price_children1=$price_children1;

                $price_children2=$list_dateavailability_available[$key]->price_children2;
                $price_children2=$price_children2-($price_children2*$percent_price->children2)/100;
                $list_dateavailability_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_dateavailability_available[$key]->price_private_room;
                $price_private_room=$price_private_room-($price_private_room*$percent_price->private_room)/100;
                $list_dateavailability_available[$key]->price_private_room=$price_private_room;


            }else{

                $amount_price=$list_mark_up_tour_dateavailability_net_price2[$virtuemart_dateavailability_price_id]['amount'];

                $price_senior=$list_dateavailability_available[$key]->price_senior;
                $price_senior=$price_senior-$amount_price->senior;
                $list_dateavailability_available[$key]->price_senior=$price_senior;

                $price_adult=$list_dateavailability_available[$key]->price_adult;
                $price_adult=$price_adult-$amount_price->adult;
                $list_dateavailability_available[$key]->price_adult=$price_adult;

                $price_teen=$list_dateavailability_available[$key]->price_teen;
                $price_teen=$price_teen-$amount_price->teen;
                $list_dateavailability_available[$key]->price_teen=$price_teen;

                $price_infant=$list_dateavailability_available[$key]->price_infant;
                $price_infant=$price_infant-$amount_price->infant;
                $list_dateavailability_available[$key]->price_infant=$price_infant;

                $price_children1=$list_dateavailability_available[$key]->price_children1;
                $price_children1=$price_children1-$amount_price->children1;
                $list_dateavailability_available[$key]->price_children1=$price_children1;

                $price_children2=$list_dateavailability_available[$key]->price_children2;
                $price_children2=$price_children2-$amount_price->children2;
                $list_dateavailability_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_dateavailability_available[$key]->price_private_room;
                $price_private_room=$price_private_room-$amount_price->private_room;
                $list_dateavailability_available[$key]->price_private_room=$price_private_room;
            }



        }

        if(count($list_virtuemart_dateavailability_price_id)==0)
        {
            vmWarn('there are no dateavailability price ');
        }

        //lấy ra các giá markup (giá trị có lãi) theo tour có net dateavailability price
        $list_mark_up_tour_dateavailability_price=array();
        if(count($list_virtuemart_dateavailability_price_id)>=1) {
            $query->clear()
                ->from('#__virtuemart_mark_up_tour_dateavailability_price_id AS mark_up_tour_dateavailability_price_id')
                ->select('mark_up_tour_dateavailability_price_id.*')
                ->where('mark_up_tour_dateavailability_price_id.virtuemart_tour_dateavailability_price_id IN ('.implode(',', $list_virtuemart_dateavailability_price_id).')')
            ;
            $list_mark_up_tour_dateavailability_price=$db->setQuery($query)->loadObjectList();
        }

        $list_mark_up_tour_dateavailability_price2=array();
        foreach($list_mark_up_tour_dateavailability_price as $mark_up_tour_dateavailability_price)
        {
            $virtuemart_tour_dateavailability_price_id=$mark_up_tour_dateavailability_price->virtuemart_tour_dateavailability_price_id;
            $list_mark_up_tour_dateavailability_price2[$virtuemart_tour_dateavailability_price_id][$mark_up_tour_dateavailability_price->type]=$mark_up_tour_dateavailability_price;
        }
        //2.tính giá thực sau khi khi có markup (có phần lãi)

        foreach($list_dateavailability_available as $key=> $dateavailability_available)
        {
            $virtuemart_dateavailability_price_id=$dateavailability_available->virtuemart_dateavailability_price_id;

            $percent_price=$list_mark_up_tour_dateavailability_price2[$virtuemart_dateavailability_price_id]['percent'];
            if(
                $percent_price->senior!=0
                ||$percent_price->adult!=0
                || $percent_price->teen!=0
                || $percent_price->infant!=0
                || $percent_price->children1!=0
                || $percent_price->children2!=0
                || $percent_price->private_room!=0)
            {
                //giá  tính theo percent thì không tính theo amount n?a
                $price_senior=$list_dateavailability_available[$key]->price_senior;
                $price_senior=$price_senior+($price_senior*$percent_price->senior)/100;
                $list_dateavailability_available[$key]->price_senior=$price_senior;

                $price_adult=$list_dateavailability_available[$key]->price_adult;
                $price_adult=$price_adult+($price_adult*$percent_price->adult)/100;
                $list_dateavailability_available[$key]->price_adult=$price_adult;

                $price_teen=$list_dateavailability_available[$key]->price_teen;
                $price_teen=$price_teen+($price_teen*$percent_price->teen)/100;
                $list_dateavailability_available[$key]->price_teen=$price_teen;

                $price_infant=$list_dateavailability_available[$key]->price_infant;
                $price_infant=$price_infant+($price_infant*$percent_price->infant)/100;
                $list_dateavailability_available[$key]->price_infant=$price_infant;

                $price_children1=$list_dateavailability_available[$key]->price_children1;
                $price_children1=$price_children1+($price_children1*$percent_price->children1)/100;
                $list_dateavailability_available[$key]->price_children1=$price_children1;

                $price_children2=$list_dateavailability_available[$key]->price_children2;
                $price_children2=$price_children2+($price_children2*$percent_price->children2)/100;
                $list_dateavailability_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_dateavailability_available[$key]->price_private_room;
                $price_private_room=$price_private_room+($price_private_room*$percent_price->private_room)/100;
                $list_dateavailability_available[$key]->price_private_room=$price_private_room;


            }else{

                $amount_price=$list_mark_up_tour_dateavailability_price2[$virtuemart_dateavailability_price_id]['amount'];

                $price_senior=$list_dateavailability_available[$key]->price_senior;
                $price_senior=$price_senior+$amount_price->senior;
                $list_dateavailability_available[$key]->price_senior=$price_senior;

                $price_adult=$list_dateavailability_available[$key]->price_adult;
                $price_adult=$price_adult+$amount_price->adult;
                $list_dateavailability_available[$key]->price_adult=$price_adult;

                $price_teen=$list_dateavailability_available[$key]->price_teen;
                $price_teen=$price_teen+$amount_price->teen;
                $list_dateavailability_available[$key]->price_teen=$price_teen;

                $price_infant=$list_dateavailability_available[$key]->price_infant;
                $price_infant=$price_infant+$amount_price->infant;
                $list_dateavailability_available[$key]->price_infant=$price_infant;

                $price_children1=$list_dateavailability_available[$key]->price_children1;
                $price_children1=$price_children1+$amount_price->children1;
                $list_dateavailability_available[$key]->price_children1=$price_children1;

                $price_children2=$list_dateavailability_available[$key]->price_children2;
                $price_children2=$price_children2+$amount_price->children2;
                $list_dateavailability_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_dateavailability_available[$key]->price_private_room;
                $price_private_room=$price_private_room+$amount_price->private_room;
                $list_dateavailability_available[$key]->price_private_room=$price_private_room;
            }



        }
        $list_dateavailability_available2=array();
        foreach($list_dateavailability_available as $dateavailability_available)
        {
            $list_dateavailability_available2[$dateavailability_available->virtuemart_product_id.'-'.$dateavailability_available->service_class_id.'-'.$dateavailability_available->virtuemart_group_size_id.'-'.$dateavailability_available->date_select]=$dateavailability_available;
        }
        //tính giá bán sau thuế
        foreach($list_dateavailability_available as $key=> $dateavailability_available)
        {
            $price_senior=$list_dateavailability_available[$key]->price_senior;
            $price_senior=$price_senior+($price_senior*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_senior=$price_senior;

            $price_adult=$list_dateavailability_available[$key]->price_adult;
            $price_adult=$price_adult+($price_adult*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_adult=$price_adult;

            $price_teen=$list_dateavailability_available[$key]->price_teen;
            $price_teen=$price_teen+($price_teen*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_teen=$price_teen;

            $price_infant=$list_dateavailability_available[$key]->price_infant;
            $price_infant=$price_infant+($price_infant*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_infant=$price_infant;

            $price_children1=$list_dateavailability_available[$key]->price_children1;
            $price_children1=$price_children1+($price_children1*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_children1=$price_children1;

            $price_children2=$list_dateavailability_available[$key]->price_children2;
            $price_children2=$price_children2+($price_children2*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_children2=$price_children2;

            $price_private_room=$list_dateavailability_available[$key]->price_private_room;
            $price_private_room=$price_private_room+($price_private_room*$dateavailability_available->tax)/100;
            $list_dateavailability_available[$key]->price_private_room=$price_private_room;
        }
        //sử lý với giá basic

        $query->clear()
            ->select('group_size_id_tour_price_id.*')
            ->from('#__virtuemart_group_size_id_tour_price_id AS group_size_id_tour_price_id')
            ->leftJoin('#__virtuemart_tour_price AS tour_price
			ON tour_price.virtuemart_price_id=group_size_id_tour_price_id.virtuemart_price_id')
            ->select('tour_price.*')
            ->where('tour_price.virtuemart_product_id='.(int)$tour_id)
            ->where('tour_price.virtuemart_service_class_id='.(int)$virtuemart_service_class_id)
            ->where('group_size_id_tour_price_id.virtuemart_group_size_id='.(int)$group_size->virtuemart_group_size_id)
        ;



        $list_price=$db->setQuery($query)->loadObjectList();
        if(count($list_dateavailability_available2)==0&&count($list_price)==0)
        {
            vmError('there are no base price  and dateavailability price');
            return false;
        }
        // lấy giá có dateavailability lọc theo điều kiên thỏa mãn danh sách ngày
        $list_price_available=array();
        foreach($list_date as $item_date)
        {
            $time_stamp_item_date=JFactory::getDate($item_date)->getTimestamp();
            foreach($list_price as $item_price_date)
            {
                $start_date=$item_price_date->sale_period_from;
                $end_date=$item_price_date->sale_period_to;
                $time_stamp_start_date=JFactory::getDate($start_date)->getTimestamp();
                $time_stamp_end_date=JFactory::getDate($end_date)->getTimestamp();
                if($time_stamp_item_date>=$time_stamp_start_date && $time_stamp_item_date<=$time_stamp_end_date)
                {
                    $item_price_date1=clone $item_price_date;
                    $item_price_date1->date_select=$item_date;
                    $list_price_available[]=$item_price_date1;
                }
            }
        }


        //lấy ra các giá markup (giá trị có lãi) theo tour có net  price


        $list_virtuemart_price_id=array();
        foreach($list_price as $item_price)
        {
            if(!in_array($item_price->virtuemart_price_id,$list_virtuemart_price_id))
            {
                $list_virtuemart_price_id[]=$item_price->virtuemart_price_id;
            }
        }


        $list_mark_up_tour_price=array();
        if(count($list_virtuemart_price_id)>=1) {
            $query->clear()
                ->from('#__virtuemart_mark_up_tour_price_id AS mark_up_tour_price_id')
                ->select('mark_up_tour_price_id.*')
                ->where('mark_up_tour_price_id.virtuemart_price_id IN ('.implode(',', $list_virtuemart_price_id).')')
            ;
            $list_mark_up_tour_price=$db->setQuery($query)->loadObjectList();
        }

        $list_mark_up_tour_price2=array();
        foreach($list_mark_up_tour_price as $mark_up_tour_price)
        {
            $virtuemart_price_id=$mark_up_tour_price->virtuemart_price_id;
            $list_mark_up_tour_price2[$virtuemart_price_id][$mark_up_tour_price->type]=$mark_up_tour_price;
        }
        //2.tính giá thực sau khi khi có markup basic (có phần lãi)

        foreach($list_price_available as $key=> $price_available)
        {
            $virtuemart_price_id=$price_available->virtuemart_price_id;

            $percent_price=$list_mark_up_tour_price2[$virtuemart_price_id]['percent'];
            if(
                $percent_price->senior!=0
                ||$percent_price->adult!=0
                || $percent_price->teen!=0
                || $percent_price->infant!=0
                || $percent_price->children1!=0
                || $percent_price->children2!=0
                || $percent_price->private_room!=0)
            {
                //giá ???c tính theo percent thì không tính theo amount n?a
                $price_senior=$list_price_available[$key]->price_senior;
                $price_senior=$price_senior+($price_senior*$percent_price->senior)/100;
                $list_price_available[$key]->price_senior=$price_senior;

                $price_adult=$list_price_available[$key]->price_adult;
                $price_adult=$price_adult+($price_adult*$percent_price->adult)/100;
                $list_price_available[$key]->price_adult=$price_adult;

                $price_teen=$list_price_available[$key]->price_teen;
                $price_teen=$price_teen+($price_teen*$percent_price->teen)/100;
                $list_price_available[$key]->price_teen=$price_teen;

                $price_infant=$list_price_available[$key]->price_infant;
                $price_infant=$price_infant+($price_infant*$percent_price->infant)/100;
                $list_price_available[$key]->price_infant=$price_infant;

                $price_children1=$list_price_available[$key]->price_children1;
                $price_children1=$price_children1+($price_children1*$percent_price->children1)/100;
                $list_price_available[$key]->price_children1=$price_children1;

                $price_children2=$list_price_available[$key]->price_children2;
                $price_children2=$price_children2+($price_children2*$percent_price->children2)/100;
                $list_price_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_price_available[$key]->price_private_room;
                $price_private_room=$price_private_room+($price_private_room*$percent_price->private_room)/100;
                $list_price_available[$key]->price_private_room=$price_private_room;


            }else{

                $amount_price=$list_mark_up_tour_price2[$virtuemart_price_id]['amount'];

                $price_senior=$list_price_available[$key]->price_senior;
                $price_senior=$price_senior+$amount_price->senior;
                $list_price_available[$key]->price_senior=$price_senior;

                $price_adult=$list_price_available[$key]->price_adult;
                $price_adult=$price_adult+$amount_price->adult;
                $list_price_available[$key]->price_adult=$price_adult;

                $price_teen=$list_price_available[$key]->price_teen;
                $price_teen=$price_teen+$amount_price->teen;
                $list_price_available[$key]->price_teen=$price_teen;

                $price_infant=$list_price_available[$key]->price_infant;
                $price_infant=$price_infant+$amount_price->infant;
                $list_price_available[$key]->price_infant=$price_infant;

                $price_children1=$list_price_available[$key]->price_children1;
                $price_children1=$price_children1+$amount_price->children1;
                $list_price_available[$key]->price_children1=$price_children1;

                $price_children2=$list_price_available[$key]->price_children2;
                $price_children2=$price_children2+$amount_price->children2;
                $list_price_available[$key]->price_children2=$price_children2;

                $price_private_room=$list_price_available[$key]->price_private_room;
                $price_private_room=$price_private_room+$amount_price->private_room;
                $list_price_available[$key]->price_private_room=$price_private_room;
            }



        }




        $list_price_available2=array();
        foreach($list_price_available as $price_available)
        {
            $list_price_available2[$price_available->virtuemart_product_id.'-'.$price_available->service_class_id.'-'.$price_available->virtuemart_group_size_id.'-'.$price_available->date_select]=$price_available;
        }
        //tính giá bán sau thuế
        foreach($list_price_available as $key=> $price_available)
        {
            $price_senior=$list_price_available[$key]->price_senior;
            $price_senior=$price_senior+($price_senior*$price_available->tax)/100;
            $list_price_available[$key]->price_senior=$price_senior;

            $price_adult=$list_price_available[$key]->price_adult;
            $price_adult=$price_adult+($price_adult*$price_available->tax)/100;
            $list_price_available[$key]->price_adult=$price_adult;

            $price_teen=$list_price_available[$key]->price_teen;
            $price_teen=$price_teen+($price_teen*$price_available->tax)/100;
            $list_price_available[$key]->price_teen=$price_teen;

            $price_infant=$list_price_available[$key]->price_infant;
            $price_infant=$price_infant+($price_infant*$price_available->tax)/100;
            $list_price_available[$key]->price_infant=$price_infant;

            $price_children1=$list_price_available[$key]->price_children1;
            $price_children1=$price_children1+($price_children1*$price_available->tax)/100;
            $list_price_available[$key]->price_children1=$price_children1;

            $price_children2=$list_price_available[$key]->price_children2;
            $price_children2=$price_children2+($price_children2*$price_available->tax)/100;
            $list_price_available[$key]->price_children2=$price_children2;

            $price_private_room=$list_price_available[$key]->price_private_room;
            $price_private_room=$price_private_room+($price_private_room*$price_available->tax)/100;
            $list_price_available[$key]->price_private_room=$price_private_room;
        }

        if(count($list_price_available2)==0)
        {
            vmWarn('there are no base price');
        }

        foreach($list_dateavailability_available2 as $key=>$value)
        {
            if(!is_object($list_price_available2[$key]))
            {
                $list_price_available2[$key]=new stdClass();
                $list_price_available2[$key]->dateavailability_price=$value;
                $list_price_available2[$key]->date_select=$value->date_select;
            }else{
                $list_price_available2[$key]->dateavailability_price=$value;
            }
        }
        if(count($list_price_available2)==0)
        {
            vmWarn('there are no dateavailability availble');
            return false;
        }
        return $list_price_available2;
    }
    public function store(&$data)
    {

        $return= parent::store($data); // TODO: Change the autogenerated stub
        return $return;
    }

    public function create_children_dateavailability($virtuemart_date_availability_id)
    {
        $query=$this->_db->getQuery(true);
        $query->delete('#__virtuemart_dateavailability')
            ->where('virtuemart_dateavailability_parent_id='.(int)$virtuemart_date_availability_id);
        $this->_db->setQuery($query);
        $ok = $this->_db->execute();
        if (!$ok) {
            $this->setError($this->_db->getErrorMsg());
            return false;
        }

        $table_dateavailability=$this->getTable();
        $table_dateavailability->load($virtuemart_date_availability_id);
        $date_type=$table_dateavailability->date_type;
        if($date_type=='day_select')
        {
            $days_seleted=explode(',',$table_dateavailability->days_seleted);
        }else{
            $sale_period_from=$table_dateavailability->sale_period_from;
            $sale_period_to=$table_dateavailability->sale_period_to;
            $days_seleted=JUtility::dateRange($sale_period_from,$sale_period_to);
            $weekly=$table_dateavailability->weekly;
            $weekly=explode(',',$weekly);
            foreach($days_seleted as $key=> $day)
            {
                $day_of_week=strtolower(date('D', strtotime( $day)));
                if(!in_array($day_of_week,$weekly))
                {
                    unset($days_seleted[$key]);
                }
            }
        }
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/vmdateavailability.php';
        foreach($days_seleted as $day) {
            $table_dateavailability->dateavailability_date = $day;
            $day=JFactory::getDate($day);
            $table_dateavailability->virtuemart_date_availability_id = 0;
            $table_dateavailability->dateavailability_code =tsmdateavailability::get_format_dateavailability_code($virtuemart_date_availability_id,$day);
            $table_dateavailability->virtuemart_dateavailability_parent_id = $virtuemart_date_availability_id;
            $ok = $table_dateavailability->store();
            if (!$ok) {
                $this->setError($table_dateavailability->getErrors());
                return false;
            }
        }
        return true;

    }

    function remove($ids)
    {
        if (!vmAccess::manager('currency')) {
            vmWarn('Insufficient permissions to remove currency');
            return false;
        }
        return parent::remove($ids);
    }

}
// pure php no closing tag