<?php
/**
 *
 * Data module for shop product
 *
 * @package	tsmart
 * @subpackage product
 * @author RickG
 * @author Max Milbers
 * @link http://www.tsmart.net
 * @copyright Copyright (c) 2004 - 2010 tsmart Team. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
 * tsmart is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * @version $Id: product.php 8970 2015-09-06 23:19:17Z Milbo $
 */
use SebastianBergmann\Money\Currency;
use SebastianBergmann\Money\Money;
// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

if(!class_exists('tmsModel'))require(VMPATH_ADMIN.DS.'helpers'.DS.'tsmmodel.php');

/**
 * Model class for shop product
 *
 * @package	tsmart
 * @subpackage product
 */
class tsmartModeljontgrouptrip extends tmsModel {

    protected $context = 'jontgrouptrip';

	/**
	 * constructs a VmModel
	 * setMainTable defines the maintable of the model
	 * @author Max Milbers
	 */
	function __construct() {
		parent::__construct();
		$this->setMainTable('departure');
	}

	/**
	 * Retrieve the detail record for the current $id if the data has not already been loaded.
	 *
	 * @author Max Milbers
	 */
	function getItem($id=0) {
		$item= $this->getData($id);
        return $item;
	}
    public function getItems()
    { require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmprice.php';
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmpromotion.php';
        $items= parent::getItems(); // TODO: Change the autogenerated stub
        // Create Money object that represents 1 EUR

// Access the Money object's monetary value converted to its base units
        foreach($items as &$item)
        {


            $item->sale_price_senior=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_senior,$item->mark_up_senior,$item->mark_up_price_senior,$item->tax,$item->mark_up_type);
            $item->sale_price_adult=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_adult,$item->mark_up_adult,$item->mark_up_price_adult,$item->tax,$item->mark_up_type);
            $item->sale_price_teen=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_teen,$item->mark_up_teen,$item->mark_up_price_teen,$item->tax,$item->mark_up_type);
            $item->sale_price_children1=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_children1,$item->mark_up_children1,$item->mark_up_price_children1,$item->tax,$item->mark_up_type);
            $item->sale_price_children2=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_children2,$item->mark_up_children2,$item->mark_up_price_children2,$item->tax,$item->mark_up_type);
            $item->sale_price_infant=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_infant,$item->mark_up_infant,$item->mark_up_price_infant,$item->tax,$item->mark_up_type);
            $item->sale_price_private_room=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_private_room,$item->mark_up_private_room,$item->mark_up_price_private_room,$item->tax,$item->mark_up_type);
            $item->sale_price_extra_bed=tsmprice::get_sale_price_by_mark_up_and_tax($item->price_extra_bed,$item->mark_up_extra_bed,$item->mark_up_price_extra_bed,$item->tax,$item->mark_up_type);
            $item->sale_promotion_price_senior=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_senior,
                $item->mark_up_promotion_senior,$item->mark_up_promotion_price_senior,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_senior,$item->mark_up_promotion_net_senior,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_adult=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_adult,
                $item->mark_up_promotion_adult,$item->mark_up_promotion_price_adult,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_adult,$item->mark_up_promotion_net_adult,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_teen=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_teen,
                $item->mark_up_promotion_teen,$item->mark_up_promotion_price_teen,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_teen,$item->mark_up_promotion_net_teen,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_children1=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_children1,
                $item->mark_up_promotion_children1,$item->mark_up_promotion_price_children1,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_children1,$item->mark_up_promotion_net_children1,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_children2=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_children2,
                $item->mark_up_promotion_children2,$item->mark_up_promotion_price_children2,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_children2,$item->mark_up_promotion_net_children2,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_infant=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_infant,
                $item->mark_up_promotion_infant,$item->mark_up_promotion_price_infant,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_infant,$item->mark_up_promotion_net_infant,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_private_room=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_private_room,
                $item->mark_up_promotion_private_room,$item->mark_up_promotion_price_private_room,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_private_room,$item->mark_up_promotion_net_private_room,$item->mark_up_promotion_net_type,
                $item->promotion_tax);

            $item->sale_promotion_price_extra_bed=vmpromotion::get_sale_promotion_price_by_mark_up_and_tax(
                $item->promotion_price_extra_bed,
                $item->mark_up_promotion_extra_bed,$item->mark_up_promotion_price_extra_bed,$item->mark_up_promotion_type,
                $item->mark_up_promotion_net_price_extra_bed,$item->mark_up_promotion_net_extra_bed,$item->mark_up_promotion_net_type,
                $item->promotion_tax);
            $item->full_charge_children1=$item->tsmart_promotion_price_id?$item->tour_promotion_price_full_charge_children1:$item->tour_price_full_charge_children1;
            $item->full_charge_children2=$item->tsmart_promotion_price_id?$item->tour_promotion_price_full_charge_children2:$item->tour_price_full_charge_children2;
        }
        return $items;
    }

    public function populateState($ordering = null, $direction = null)
    {
        $app = JFactory::getApplication('site');

        // Load the filter state.
        $total_passenger_from_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_from_12_years_old', 'filter_total_passenger_from_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_from_12_years_old', $total_passenger_from_12_years_old);

        $total_passenger_under_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_under_12_years_old', 'filter_total_passenger_under_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_under_12_years_old', $total_passenger_under_12_years_old);


        $start_date = $this->getUserStateFromRequest($this->context . '.filter.start_date', 'filter_start_date', '', 'string');
        $this->setState('filter.start_date', $start_date);

        $month = $this->getUserStateFromRequest($this->context . '.filter.month', 'filter_month', '', 'string');
        $this->setState('filter.month', $month);

    }

    function getListQuery()
	{
        require_once JPATH_ROOT.'/administrator/components/com_tsmart/helpers/tsmgroupsize.php';
        $app=JFactory::getApplication();
        $input=$app->input;
        $tsmart_product_id=$input->getInt('tsmart_product_id',0);
        $tsmart_departure_id=$this->getState('filter.tsmart_departure_id');
		$db = JFactory::getDbo();
		$query=$db->getQuery(true);
        $query->select('departure.tsmart_departure_id,departure.departure_date,departure.departure_code,departure.allow_passenger,departure.tsmart_product_id')
            ->from('#__tsmart_departure AS departure')
            ->where('departure.tsmart_departure_parent_id IS NOT NULL')
            ->where('departure.departure_date>='.$db->quote(JFactory::getDate()->toSql()))
            ->innerJoin('#__tsmart_tour_price AS tour_price ON (tour_price.sale_period_from <=departure.departure_date AND departure.departure_date<=tour_price.sale_period_to)')
            ->where('tour_price.tsmart_product_id=departure.tsmart_product_id')
            ->where('tour_price.tsmart_service_class_id=departure.tsmart_service_class_id')
            ->select('tour_price.tsmart_price_id')
            ->select('tour_price.full_charge_children1 AS tour_price_full_charge_children1,tour_price.full_charge_children2 AS tour_price_full_charge_children2,tour_price.tax')
            ->where('departure.tsmart_product_id='.(int)$tsmart_product_id)
            ->where('tour_price.tsmart_price_id IS NOT NULL')
            ->leftJoin('#__tsmart_group_size_id_tour_price_id AS group_size_id_tour_price_id ON group_size_id_tour_price_id.tsmart_price_id=tour_price.tsmart_price_id')
            ->select('
                group_size_id_tour_price_id.price_senior AS price_senior,
                group_size_id_tour_price_id.price_adult AS price_adult,
                group_size_id_tour_price_id.price_teen AS price_teen,
                group_size_id_tour_price_id.price_infant AS price_infant,
                group_size_id_tour_price_id.price_children1 AS price_children1,
                group_size_id_tour_price_id.price_children2 AS price_children2,
                group_size_id_tour_price_id.price_private_room AS price_private_room,
                group_size_id_tour_price_id.price_extra_bed AS price_extra_bed

            ')
            ->leftJoin('#__tsmart_group_size AS group_size ON group_size.tsmart_group_size_id=group_size_id_tour_price_id.tsmart_group_size_id')
            ->where('group_size.type='.$query->q(tsmGroupSize::FLAT_PRICE))
            ->select('tour_price.sale_period_from AS tour_price_sale_period_from,tour_price.sale_period_to AS tour_price_sale_period_to')
            ->innerJoin('#__tsmart_service_class AS service_class ON tour_price.tsmart_service_class_id=service_class.tsmart_service_class_id')
            ->select('service_class.service_class_name')

            ->leftJoin('#__tsmart_itinerary AS itinerary ON itinerary.tsmart_product_id=tour_price.tsmart_product_id')
            ->select('count(distinct itinerary.tsmart_itinerary_id) AS total_day ')
            ->leftJoin('#__tsmart_cityarea AS cityarea ON cityarea.tsmart_cityarea_id=itinerary.tsmart_cityarea_id')
            ->leftJoin('#__tsmart_states AS states ON states.tsmart_state_id=cityarea.tsmart_state_id')
            ->leftJoin('#__tsmart_countries AS countries ON countries.tsmart_country_id=states.tsmart_country_id')
            ->select('GROUP_CONCAT(
                    CONCAT(states.state_name,",",countries.country_name) SEPARATOR ";"
            ) AS list_destination')

            ;
        $query->group('departure.tsmart_departure_id')
            ->order('departure.departure_date')
            ;
        $query->innerJoin('#__tsmart_mark_up_tour_price_id AS mark_up_tour_price_id ON mark_up_tour_price_id.tsmart_price_id=tour_price.tsmart_price_id')
            ->select('
            mark_up_tour_price_id.price_senior AS mark_up_price_senior,
            mark_up_tour_price_id.price_adult AS mark_up_price_adult,
            mark_up_tour_price_id.price_teen AS mark_up_price_teen,
            mark_up_tour_price_id.price_infant AS mark_up_price_infant,
            mark_up_tour_price_id.price_children1 AS mark_up_price_children1,
            mark_up_tour_price_id.price_children2 AS mark_up_price_children2,
            mark_up_tour_price_id.price_private_room AS mark_up_price_private_room,
            mark_up_tour_price_id.price_extra_bed AS mark_up_price_extra_bed,
            mark_up_tour_price_id.senior AS mark_up_senior,
            mark_up_tour_price_id.adult AS mark_up_adult,
            mark_up_tour_price_id.teen AS mark_up_teen,
            mark_up_tour_price_id.children1 AS mark_up_children1,
            mark_up_tour_price_id.children2 AS mark_up_children2,
            mark_up_tour_price_id.price_teen AS mark_up_teen,
            mark_up_tour_price_id.infant AS mark_up_infant,
            mark_up_tour_price_id.private_room AS mark_up_private_room,
            mark_up_tour_price_id.extra_bed AS mark_up_extra_bed,
            mark_up_tour_price_id.type AS mark_up_type
            ')

            ->leftJoin('#__tsmart_tour_promotion_price AS tour_promotion_price ON departure.departure_date>= tour_promotion_price.sale_period_from AND departure.departure_date<=tour_promotion_price.sale_period_to AND tour_promotion_price.tsmart_product_id=departure.tsmart_product_id AND tour_promotion_price.tsmart_service_class_id=departure.tsmart_service_class_id')
            ->select('tour_promotion_price.tsmart_promotion_price_id, tour_promotion_price.full_charge_children1 AS tour_promotion_price_full_charge_children1,tour_promotion_price.full_charge_children2 AS tour_promotion_price_full_charge_children2,tour_promotion_price.tax AS promotion_tax')
            ->leftJoin('#__tsmart_group_size_id_tour_promotion_price_id AS group_size_id_tour_promotion_price_id ON group_size_id_tour_promotion_price_id.tsmart_promotion_price_id=tour_promotion_price.tsmart_promotion_price_id')
            ->select('
                    group_size_id_tour_promotion_price_id.price_senior AS promotion_price_senior,
                    group_size_id_tour_promotion_price_id.price_adult AS promotion_price_adult,
                    group_size_id_tour_promotion_price_id.price_teen AS promotion_price_teen,
                    group_size_id_tour_promotion_price_id.price_children1 AS promotion_price_children1,
                    group_size_id_tour_promotion_price_id.price_children2 AS promotion_price_children2,
                    group_size_id_tour_promotion_price_id.price_infant AS promotion_price_infant,
                    group_size_id_tour_promotion_price_id.price_private_room AS promotion_price_private_room,
                    group_size_id_tour_promotion_price_id.price_extra_bed AS promotion_price_extra_bed
                    ')
            ->leftJoin('#__tsmart_mark_up_tour_promotion_net_price_id AS mark_up_tour_promotion_net_price_id ON mark_up_tour_promotion_net_price_id.tsmart_promotion_price_id=tour_promotion_price.tsmart_promotion_price_id')
            ->select('
                    mark_up_tour_promotion_net_price_id.price_senior AS mark_up_promotion_net_price_senior,
                    mark_up_tour_promotion_net_price_id.price_adult AS mark_up_promotion_net_price_adult,
                    mark_up_tour_promotion_net_price_id.price_teen AS mark_up_promotion_net_price_teen,
                    mark_up_tour_promotion_net_price_id.price_infant AS mark_up_promotion_net_price_infant,
                    mark_up_tour_promotion_net_price_id.price_children1 AS mark_up_promotion_net_price_children1,
                    mark_up_tour_promotion_net_price_id.price_children2 AS mark_up_promotion_net_price_children2,
                    mark_up_tour_promotion_net_price_id.price_private_room AS mark_up_promotion_net_price_private_room,
                    mark_up_tour_promotion_net_price_id.price_extra_bed AS mark_up_promotion_net_price_extra_bed,
                    mark_up_tour_promotion_net_price_id.senior AS mark_up_promotion_net_senior,
                    mark_up_tour_promotion_net_price_id.adult AS mark_up_promotion_net_adult,
                    mark_up_tour_promotion_net_price_id.teen AS mark_up_promotion_net_teen,
                    mark_up_tour_promotion_net_price_id.children1 AS mark_up_promotion_net_children1,
                    mark_up_tour_promotion_net_price_id.children2 AS mark_up_promotion_net_children2,
                    mark_up_tour_promotion_net_price_id.infant AS mark_up_promotion_net_infant,
                    mark_up_tour_promotion_net_price_id.private_room AS mark_up_promotion_net_private_room,
                    mark_up_tour_promotion_net_price_id.extra_bed AS mark_up_promotion_net_extra_bed,
                    mark_up_tour_promotion_net_price_id.type AS mark_up_promotion_net_type
            ')

            ->leftJoin('#__tsmart_mark_up_tour_promotion_price_id AS mark_up_tour_promotion_price_id ON mark_up_tour_promotion_price_id.tsmart_promotion_price_id=tour_promotion_price.tsmart_promotion_price_id')
            ->select('
                    mark_up_tour_promotion_price_id.price_senior AS mark_up_promotion_price_senior,
                    mark_up_tour_promotion_price_id.price_adult AS mark_up_promotion_price_adult,
                    mark_up_tour_promotion_price_id.price_teen AS mark_up_promotion_price_teen,
                    mark_up_tour_promotion_price_id.price_infant AS mark_up_promotion_price_infant,
                    mark_up_tour_promotion_price_id.price_children1 AS mark_up_promotion_price_children1,
                    mark_up_tour_promotion_price_id.price_children2 AS mark_up_promotion_price_children2,
                    mark_up_tour_promotion_price_id.price_private_room AS mark_up_promotion_price_private_room,
                    mark_up_tour_promotion_price_id.price_extra_bed AS mark_up_promotion_price_extra_bed,
                    mark_up_tour_promotion_price_id.senior AS mark_up_promotion_senior,
                    mark_up_tour_promotion_price_id.adult AS mark_up_promotion_adult,
                    mark_up_tour_promotion_price_id.teen AS mark_up_promotion_teen,
                    mark_up_tour_promotion_price_id.children1 AS mark_up_promotion_children1,
                    mark_up_tour_promotion_price_id.children2 AS mark_up_promotion_children2,
                    mark_up_tour_promotion_price_id.infant AS mark_up_promotion_infant,
                    mark_up_tour_promotion_price_id.extra_bed AS mark_up_promotion_extra_bed,
                    mark_up_tour_promotion_price_id.private_room AS mark_up_promotion_private_room,
                    mark_up_tour_promotion_price_id.type AS mark_up_promotion_type
            ')
        ;
        if($tsmart_departure_id)
        {
            $query->where('departure.tsmart_departure_id='.(int)$tsmart_departure_id);
        }
        //echo $query->dump();
		return $query;
	}




}
// pure php no closing tag
