<?php
/**
 *
 * Product table
 *
 * @package    tsmart
 * @subpackage Product
 * @author Max Milbers
 * @link http://www.tsmart.net
 * @copyright Copyright (c) 2009 - 2014 tsmart Team. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
 * tsmart is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * @version $Id: products.php 8557 2014-11-09 21:06:17Z Milbo $
 */

defined('_JEXEC') or die('Restricted access');

if (!class_exists('tsmTable')) require(VMPATH_ADMIN . DS . 'helpers' . DS . 'tsmtable.php');


class TableProducts extends tsmTable
{

    var $tsmart_product_id = 0;
    var $product_name = '';
    var $tour_operator = '';
    var $tour_length = 0;
    var $start_city = 0;
    var $product_code = 0;
    var $end_city = 0;
    var $tsmart_tour_type_id = 0;
    var $tsmart_tour_style_id = 0;
    var $tsmart_physicalgrade_id = 0;
    var $meta_title = 0;
    var $meta_keyword = 0;
    var $travel_route = 0;
    var $latitude = 0;
    var $longitude = 0;
    var $location = "";
    var $image_map = 0;
    var $radius = 0;
    var $meta_description = 0;
    var $trip_high_light = 0;
    var $trip_overview = 0;
    var $important_note = 0;
    var $trip_policy = 0;
    var $term_condition = 0;
    var $min_person = 0;
    var $max_person = 0;
    var $min_age = 0;
    var $max_age = 0;
    var $price_type = '';
    var $tsmart_tour_section_id = 0;
    var $shared					= 0;
    var $published				= 0;
    function __construct($db)
    {
        parent::__construct('#__tsmart_products', 'tsmart_product_id', $db);
        $this->setUniqueName('product_name');
        $this->setTranslatable(array(
            'product_name',
            'meta_title',
            'meta_keyword',
            'travel_route',
            'meta_description',
            'trip_high_light',
            'trip_overview',
            'important_note',
            'trip_policy',
            'activity_description',
            'inclusions',
            'exclusions',
            'trip_note_heading',
            'trip_note_content',
            'term_condition'
        ));
        $this->setLoggable();

        $this->setOrderable();

    }
    public function bindChecknStore(&$data, $preload = false)
    {
        $db=JFactory::getDbo();
        $query=$db->getQuery(true);
        $query->select('products_en_gb.tsmart_product_id')
            ->from('#__tsmart_products AS products')
            ->leftJoin('#__tsmart_products_en_gb AS products_en_gb USING(tsmart_product_id)')
            ->where('products_en_gb.tsmart_product_id!='.(int)$data['tsmart_product_id'])
            ->where('products_en_gb.product_name = '.$query->q("{$data['product_name']}"))
        ;
        $db->setQuery($query);
        $list_tour=$db->loadObjectList();
        if(count($list_tour)>0)
        {
            vmError('tour name exists, please select other tour name');
            return false;
        }
        return parent::bindChecknStore($data, $preload); // TODO: Change the autogenerated stub
    }

    public function check()
    {
        return true;
        echo "<pre>";
        print_r($this->getTranslatableFields());
        echo "</pre>";
        die;

    }

}
// pure php no closing tag
