<?php
/**
 *
 * Data module for shop product
 *
 * @package	VirtueMart
 * @subpackage product
 * @author RickG
 * @author Max Milbers
 * @link http://www.virtuemart.net
 * @copyright Copyright (c) 2004 - 2010 VirtueMart Team. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
 * VirtueMart is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * @version $Id: product.php 8970 2015-09-06 23:19:17Z Milbo $
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

if(!class_exists('VmModel'))require(VMPATH_ADMIN.DS.'helpers'.DS.'vmmodel.php');

/**
 * Model class for shop product
 *
 * @package	VirtueMart
 * @subpackage product
 */
class VirtueMartModeljontgrouptrip extends VmModel {

    protected $context = 'jontgrouptrip';

	/**
	 * constructs a VmModel
	 * setMainTable defines the maintable of the model
	 * @author Max Milbers
	 */
	function __construct() {
		parent::__construct();
		$this->setMainTable('price');
	}

	/**
	 * Retrieve the detail record for the current $id if the data has not already been loaded.
	 *
	 * @author Max Milbers
	 */
	function getItem($id=0) {
		$item= $this->getData($id);
        return $item;
	}
    public function getItems()
    {
        $items= parent::getItems(); // TODO: Change the autogenerated stub
        foreach($items as &$item)
        {
            $type=$item->mark_up_type;
            $tax=$item->tax/100;
            if($type=='amount')
            {
                $price_senior=$item->price_senior+$item->mark_up_price_senior;
                $item->price_senior=round($price_senior+$price_senior.$tax);


                $price_adult=$item->price_adult+$item->mark_up_price_adult;
                $item->price_adult=round($price_adult+$price_adult.$tax);


                $price_teen=$item->price_teen+$item->mark_up_price_teen;
                $item->price_teen=round($price_teen+$price_teen.$tax);


                $price_infant=$item->price_infant+$item->mark_up_price_infant;
                $item->price_infant=round($price_infant+$price_infant.$tax);


                $price_children1=$item->price_children1+$item->mark_up_price_children1;
                $item->price_children1=round($price_children1+$price_children1.$tax);


                $price_children2=$item->price_children2+$item->mark_up_price_children2;
                $item->price_children2=round($price_children2+$price_children2.$tax);


                $price_private_room=$item->price_private_room+$item->mark_up_price_private_room;
                $item->price_private_room=round($price_private_room+$price_private_room.$tax);


                $extra_bed=$item->extra_bed+$item->mark_up_extra_bed;
                $item->extra_bed=round($extra_bed+$extra_bed.$tax);


            }else{
                $price_senior=$item->price_senior+$item->price_senior.$item->mark_up_senior/100;
                $item->price_senior=round($price_senior+$price_senior.$tax);


                $price_adult=$item->price_adult+$item->price_adult*$item->mark_up_adult/100;
                $item->price_adult=round($price_adult+$price_adult.$tax);


                $price_teen=$item->price_teen+$item->price_teen*$item->mark_up_teen/100;
                $item->price_teen=round($price_teen+$price_teen.$tax);


                $price_infant=$item->price_infant+$item->price_infant*$item->mark_up_infant/100;
                $item->price_infant=round($price_infant+$price_infant.$tax);


                $price_children1=$item->price_children1+$item->price_children1*$item->mark_up_children1/100;
                $item->price_children1=round($price_children1+$price_children1.$tax);


                $price_children2=$item->price_children2+$item->price_children2*$item->mark_up_children2/100;
                $item->price_children2=round($price_children2+$price_children2.$tax);


                $price_private_room=$item->price_private_room+$item->price_private_room*$item->mark_up_private_room/100;
                $item->price_private_room=round($price_private_room+$price_private_room.$tax);


                $extra_bed=$item->extra_bed+$item->extra_bed*$item->mark_up_extra_bed/100;
                $item->extra_bed=round($extra_bed+$extra_bed.$tax);

            }
        }
        return $items;
    }

    public function populateState($ordering = null, $direction = null)
    {
        $app = JFactory::getApplication('site');

        // Load the filter state.
        $total_passenger_from_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_from_12_years_old', 'filter_total_passenger_from_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_from_12_years_old', $total_passenger_from_12_years_old);

        $total_passenger_under_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_under_12_years_old', 'filter_total_passenger_under_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_under_12_years_old', $total_passenger_under_12_years_old);


        $start_date = $this->getUserStateFromRequest($this->context . '.filter.start_date', 'filter_start_date', '', 'string');
        $this->setState('filter.start_date', $start_date);

        $month = $this->getUserStateFromRequest($this->context . '.filter.month', 'filter_month', '', 'string');
        $this->setState('filter.month', $month);

    }

    function getListQuery()
	{
        $app=JFactory::getApplication();
        $input=$app->input;
        $virtuemart_product_id=$input->getInt('virtuemart_product_id',0);
		$db = JFactory::getDbo();
		$query=$db->getQuery(true);
        $query->select('departure')
            ->from('#__virtuemart_departure AS departure')
            ->where('departure.virtuemart_product_id='.(int)$virtuemart_product_id)

            ;
        echo $query->dump();
		return $query;
	}




}
// pure php no closing tag
