<?php
/**
 *
 * Data module for shop product
 *
 * @package	VirtueMart
 * @subpackage product
 * @author RickG
 * @author Max Milbers
 * @link http://www.virtuemart.net
 * @copyright Copyright (c) 2004 - 2010 VirtueMart Team. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php
 * VirtueMart is free software. This version may have been modified pursuant
 * to the GNU General Public License, and as distributed it includes or
 * is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 * @version $Id: product.php 8970 2015-09-06 23:19:17Z Milbo $
 */

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die('Restricted access');

if(!class_exists('VmModel'))require(VMPATH_ADMIN.DS.'helpers'.DS.'vmmodel.php');

/**
 * Model class for shop product
 *
 * @package	VirtueMart
 * @subpackage product
 */
class VirtueMartModelTrip extends VmModel {

    protected $context = 'trip';

	/**
	 * constructs a VmModel
	 * setMainTable defines the maintable of the model
	 * @author Max Milbers
	 */
	function __construct() {
		parent::__construct();
		$this->setMainTable('price');
	}

	/**
	 * Retrieve the detail record for the current $id if the data has not already been loaded.
	 *
	 * @author Max Milbers
	 */
	function getItem($id=0) {
		$item= $this->getData($id);
        return $item;
	}
    public function getItems()
    {
        $items= parent::getItems(); // TODO: Change the autogenerated stub
        return $items;
    }

    public function populateState($ordering = null, $direction = null)
    {
        $app = JFactory::getApplication('site');

        // Load the filter state.
        $total_passenger_from_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_from_12_years_old', 'filter_total_passenger_from_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_from_12_years_old', $total_passenger_from_12_years_old);

        $total_passenger_under_12_years_old = $this->getUserStateFromRequest($this->context . '.filter.total_passenger_under_12_years_old', 'filter_total_passenger_under_12_years_old', 0, 'int');
        $this->setState('filter.total_passenger_under_12_years_old', $total_passenger_under_12_years_old);


        $start_date = $this->getUserStateFromRequest($this->context . '.filter.start_date', 'filter_start_date', '', 'string');
        $this->setState('filter.start_date', $start_date);

    }

    function getListQuery()
	{
        $app=JFactory::getApplication();
        $input=$app->input;
        $virtuemart_product_id=$input->getInt('virtuemart_product_id',0);
		$db = JFactory::getDbo();
		$query=$db->getQuery(true);
		$query->select('tour_price.*,group_size_id_tour_price_id.*,service_class.service_class_name')
            ->where('tour_price.virtuemart_product_id='.(int)$virtuemart_product_id)
			->from('#__virtuemart_tour_price AS tour_price')
            ->leftJoin('#__virtuemart_service_class AS service_class USING(virtuemart_service_class_id)')
            ->leftJoin('#__virtuemart_itinerary AS itinerary USING(virtuemart_product_id)')
            ->select('count(distinct itinerary.virtuemart_itinerary_id) AS total_day ')
            ->leftJoin('#__virtuemart_cityarea AS cityarea ON cityarea.virtuemart_cityarea_id=itinerary.virtuemart_cityarea_id')
            ->leftJoin('#__virtuemart_states AS states ON states.virtuemart_state_id=cityarea.virtuemart_state_id')
            ->leftJoin('#__virtuemart_countries AS countries ON countries.virtuemart_country_id=states.virtuemart_country_id')
            ->select('GROUP_CONCAT(
                    CONCAT(states.state_name,",",countries.country_name) SEPARATOR ";"
            ) AS list_destination')
            ->leftJoin('#__virtuemart_group_size_id_tour_price_id AS group_size_id_tour_price_id USING(virtuemart_price_id)')
            ->leftJoin('#__virtuemart_group_size AS group_size ON group_size.virtuemart_group_size_id=group_size_id_tour_price_id.virtuemart_group_size_id')


		;
        if ($start_date = $this->getState('filter.start_date'))
        {
            $start_date=JFactory::getDate($start_date);
            $query->where('tour_price.sale_period_from<='.$query->quote($start_date->toSql()));
            $query->where('tour_price.sale_period_to>='.$query->quote($start_date->toSql()));
        }
        if ($total_passenger_from_12_years_old = $this->getState('filter.total_passenger_from_12_years_old'))
        {
            $query->where('group_size.from<='.(int)$total_passenger_from_12_years_old);
            $query->where('group_size.to>='.(int)$total_passenger_from_12_years_old);
        }

		$query->order('tour_price.virtuemart_price_id');
        $query->group('tour_price.virtuemart_service_class_id');
        echo $query->dump();
		return $query;
	}




}
// pure php no closing tag
